### PR TITLE
[O11Y-217] always use int64 to represent row indexes

### PR DESCRIPTION
**Pull request by achille-roussel**
This PR unifies external APIs to always use `int64` instead of `int` for row indexes.

### CODE REVIEW

**Comment by pelletier** [comment]
What's the motivation behind this change?

**Comment by achille-roussel** [comment]
Go makes no strong guarantees on the capacity of a `int` value, it's "at least 32 bits", and there may be more than 2 billion rows to in a parquet file (or set of merged files).

**Comment by pelletier** [comment]
I see a bunch of casting like `int64(len(...))`. I'd expect that value to be at most the maximum value of `int`. When `int` is only 32 bits, isn't the program still not going to be able to handle sets of more than 2B values?

**Comment by achille-roussel** [comment]
> I see a bunch of casting like int64(len(...)). I'd expect that value to be at most the maximum value of int. When int is only 32 bits, isn't the program still not going to be able to handle sets of more than 2B values?

On 32 bits systems, I would expect that the maximum memory addressable by a program would be 2GiB, so it wouldn't be possible to create slices which exceed the available memory.

**Review by kevinburkesegment — APPROVED** [review]

**Comment by pelletier** [comment]
> On 32 bits systems, I would expect that the maximum memory addressable by a program would be 2GiB, so it wouldn't be possible to create slices which exceed the available memory.

I'd expect that too. Is that a change to future-proof the API then?

**Pull request merged**
