### PR TITLE
Add test reproducing unexpected fixed size binary dict error

### PR DESCRIPTION
**Pull request by brancz**
I don't have a fix for this yet, but I noticed that dicts of repeated UUIDs don't appear to work as expected.

This test currently fails with:

```
--- FAIL: TestWriterRepeatedUUIDDict (0.00s)
    writer_test.go:559: reading dictionary of column "list": reading parquet dictionary of fixed-length binary values of size 16: length of fixed byte array is not a multiple of its size: size=16 length=1
FAIL
```

### CODE REVIEW

**Comment by kevinburkesegment** [comment]
I can take this one, it might help me get more familiar with what the code is doing.

**Comment by kevinburkesegment** [comment]
Currently troubleshooting this - it looks like we're writing the right UUID data to the file/buffer, looking at the read path now.

**Comment by kevinburkesegment** [comment]
@brancz I submitted #113 which includes the fix - mind if I close?

**Comment by brancz** [comment]
Of course! Awesome!

**Pull request closed without merging**
