### PR TITLE
Fix SeekToRow on mergedRowGroupRows

### PR DESCRIPTION
**Pull request by asubiotto**
When a Read is performed after SeekToRow on mergedRowGroups, the rowIndex is checked against the seek index and advanced until the rowIndex == seek index. Previously, the rowIndex was not advanced in the normal read path, resulting in mistakenly dropping unread rows when advancing the rowIndex.

### CODE REVIEW

**Comment by asubiotto** [comment]
cc @achille-roussel

**Comment by asubiotto** [comment]
CI should be green now. The issue was returning `n == 0` on `err == io.EOF`.

**Comment by asubiotto** [comment]
Friendly ping @achille-roussel (I apologize if you're still on PTO)

**Review by achille-roussel — APPROVED** [review]
Thanks for the reminder! The change looks good 👍

**Pull request merged**
