### PR TITLE
Add the ability to pass Parquet tags on map key and values

### LINKED ISSUE #256: Add ability to set properties on key and value of a Parquet map
Currently when defining a Parquet map:

```
type A struct {
  B map[string]string `parquet:","`
}
```

We don't have the ability to set the properties of the key or value for that map.

One possibility is to add something similar to the following:

```
type A struct {
  B map[string]string `parquet:",key(dict,zstd)"`
}
```

### PR DESCRIPTION
**Pull request by Pryz**
Fixes #256

### CODE REVIEW

**Comment by achille-roussel** [comment]
We discussed offline the option to use a different struct tag name for the key, e.g. `key`, `mapkey` or `parquet-key`, which has advantages over the `key=` prefix:

- the grouping of attributes for the map key help with readability
- there is no need for repetition like there is with the `key=` prefix

Did you get a chance to give this more thoughts?

**Comment by Pryz** [comment]
Did some experimentation and went with the `parquet-key` tag.

Example:
```
type Spans struct {
	Attributes map[string]json.RawMessage `parquet:"attributes,optional,json,zstd" parquet-key:"zstd"`
}
```

**Review by achille-roussel — APPROVED** [review]
The change is looking good!

**Comment by Pryz** [comment]
Thanks for the review !

**Pull request merged**
